<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/styles/main.css" type="text/css" rel="stylesheet" />
    <?php echo $this->headLink( ) ?>
    <title>WMDev Project Shell</title>
    <script type="text/javascript" src="/scripts/mootools-1.2-core-yc.js"></script>
    <script type="text/javascript" src="/scripts/mootools-1.2-more.js"></script>
    <?php echo $this->headScript( ) ?>
  </head>

  <body>

    <?php echo $this->layout( )->content ?>

  </body>

</html>
