<tr>
  <td class="clientCode"><?php echo $this->escape( $this->clientCode ) ?></td>
  <td><?php echo $this->escape( $this->count ) ?></td>
  <td>&pound;<?php echo $this->escape( $this->paymentsTotal ) ?></td>
  <td><?php echo $this->escape( $this->postOfficeCount ) ?></td>
  <td><?php echo $this->escape( $this->payPointCount ) ?></td>
  <td><?php echo $this->escape( $this->payZoneCount ) ?></td>
  <td><?php echo $this->escape( $this->ePayCount ) ?></td>
  <td><?php echo $this->escape( $this->terminalDebitCardCount ) ?></td>
  <td><?php echo $this->escape( $this->terminalCreditCardCount) ?></td>
  <td><?php echo $this->escape( $this->terminalCashCount ) ?></td>
  <td><?php echo $this->escape( $this->woolworthsCount ) ?></td>
  <td><?php echo $this->escape( $this->directDebitCount ) ?></td>
  <td><?php echo $this->escape( $this->chequeCount ) ?></td>
  <td><?php echo $this->escape( $this->cashCount ) ?></td>
</tr>
