<?php 

    // Work out the max number of payments. Default value of 1 because the 
    // actual payment will always be one. Original or capped payments might be 
    // more
    if ( count( $this->originalPayments ) >= count( $this->cappedPayments ) )
    {

        $numberOfPayments = count( $this->originalPayments );
        
    }
    else if ( count( $this->cappedPayments ) > count( $this->originalPayments ) )
    {
        
        $numberOfPayments = count( $this->cappedPayments );
        
    }
    else 
    {

        $numberOfPayments = 1;
        
    }
    
    // Get the keys for the original payments
    $originalPaymentKeys = array_keys( $this->originalPayments );
    
    $backgroundStyle = $this->valueToggle( 'background-color: #FFFFEE', 'background-color: #FFFFFF' );
    
    // Having worked that out, loop through that number    
    for( $loop = 0; $loop < $numberOfPayments; $loop++ )
    {

        // First time round, open with a standard <tr> and then output the 
        // reference and date info.
        if ( $loop == 0 )
        {
?>
<tr>
  <td><?php echo $this->escape( $this->reference ) ?></td>
  <td><?php echo $this->escape( date( 'd/m/Y', strtotime( $this->paymentDate ) ) ) ?></td>
<?php 
        }
        else 
        {
?>
<tr style="border-top: #DDDDDD 1px solid;">
  <td>&nbsp;</td>
  <td>&nbsp;</td>
<?php          
        }
        
        // If there is an original payment set for the current loop, display it
        if ( isset( $originalPaymentKeys[$loop] ) )
        { 
?>
  <td class="amount">&pound;<?php echo $this->escape( $this->originalPayments[$originalPaymentKeys[$loop]] ) ?></td>
<?php
        }
        else 
        {
?>
  <td class="amount">&nbsp;</td>
<?php
        }
        
        if ( $loop == 0 )
        {
?>
  <td class="amount">&pound;<?php echo $this->escape( $this->amount ) ?></td>
<?php 
        }
        else 
        {
?>
  <td class="amount">&nbsp;</td>
<?php
        }
        
        if ( isset( $this->cappedPayments[$loop] ) )
        {
?>
  <td class="amount">&pound;<?php echo $this->escape( $this->cappedPayments[$loop] ) ?></td>
<?php
        }
        else 
        {
?>
  <td class="amount">&nbsp;</td>
<?php
        }
?>
</tr>
<?php
    }
?>