<h1>Import Status</h1>

<h2>Currently Processing</h2>

<table>
  <tr>
    <th>Time</th>
    <th>Date</th>
    <th>User</th>
    <th>Files</th>
    <th>Imported</th>
    <th>Failed</th>
    <th>&nbsp;</th>
  </tr>
  
  <!--  Loop through a partial here -->
  
</table>

<h2>Completed</h2>

<table>
  <tr>
    <th>Time</th>
    <th>Date</th>
    <th>User</th>
    <th>Files</th>
    <th>Imported</th>
    <th>Failed</th>
    <th>&nbsp;</th>
  </tr>
  
  <!--  Loop through a partial here -->
  
</table>

